import test from 'node:test';import assert from 'node:assert/strict';
import router from '../src/router.js';import {setup,ID,CLEAN,MARKED,imageMock} from './security-helpers.mjs';
function req(mode,options={}){return new Request(`https://recast.test/api/admin/print-finish${mode?'':`?requestId=${ID}`}`,{method:mode?'POST':'GET',headers:{authorization:'Bearer owner-test-secret','content-type':'application/json',...options.headers},...(mode?{body:JSON.stringify({requestId:ID,mode,confirmBillable:true,...options.body})}:{})})}
async function fixture(){const env=await setup();let infos=0;env.IMAGES.info=async()=>++infos%3===1?{width:768,height:960}:{width:1536,height:1920};env.AI={run(){throw Error('FLUX must not run')}};return env;}
test('owner authentication precedes all image operations',async()=>{const env=await fixture();const r=await router.fetch(req('preserve',{headers:{authorization:''}}),env,{});assert.equal(r.status,401);assert.equal(env.IMAGES.operations.length,0)});
test('GET never starts an upscale',async()=>{const env=await fixture();const r=await router.fetch(req(),env,{});assert.equal(r.status,200);assert.equal((await r.json()).candidates[0].status,'not_started');assert.equal(env.IMAGES.operations.length,0)});
test('finish preserves master, returns marked full-size preview and caches duplicate submission',async()=>{
 const env=await fixture();const before=await (await env.ARTWORK.get(`requests/${ID}/preview.b64`)).text();
 const r=await router.fetch(req('preserve'),env,{});const data=await r.json();assert.equal(r.status,200);const c=data.candidates[0];assert.equal(c.status,'succeeded');assert.equal(c.width,1536);assert.equal(c.preview,`data:image/jpeg;base64,${MARKED.toString('base64')}`);assert.equal(c.watermarked,true);assert.equal(c.usage.actualCostUsd,null);
 assert.equal(await (await env.ARTWORK.get(`requests/${ID}/preview.b64`)).text(),before);
 assert.ok(env.IMAGES.operations.some(([op,o])=>op==='transform'&&o.upscale==='interpolate'&&o.width===1536));
 assert.ok(env.IMAGES.operations.some(([op,o])=>op==='transform'&&o.fit==='scale-down'&&o.width===1536));
 const count=env.IMAGES.operations.length;await router.fetch(req('preserve'),env,{});await router.fetch(req(),env,{});assert.equal(env.IMAGES.operations.length,count);
 assert.equal(JSON.stringify(data).includes(CLEAN.toString('base64')),false);
});
test('enhanced is explicit and cannot change customer checkout state',async()=>{const env=await fixture();const r=await router.fetch(req('enhanced'),env,{});assert.equal((await r.json()).candidates[1].status,'succeeded');assert.ok(env.IMAGES.operations.some(([op,o])=>op==='transform'&&o.upscale==='generate'));assert.equal(env.ARTWORK.objects.has(`requests/${ID}/final-print.jpg`),false)});
test('concurrent submissions make one upscale per source and mode',async()=>{const env=await fixture();env.IMAGES.info=async(stream)=>{const bytes=Buffer.from(await new Response(stream).arrayBuffer());return bytes.equals(CLEAN)?{width:768,height:960}:{width:1536,height:1920}};await Promise.all(Array.from({length:8},()=>router.fetch(req('enhanced'),env,{})));assert.equal(env.IMAGES.operations.filter(([op,o])=>op==='transform'&&o.upscale==='generate').length,1)});
test('failed/ambiguous finish is not automatically resubmitted or exposed clean',async()=>{const env=await fixture();env.IMAGES=imageMock({fail:true});const first=await (await router.fetch(req('enhanced'),env,{})).json();assert.equal(first.candidates[1].status,'failed');assert.equal(first.candidates[1].preview,undefined);const count=env.IMAGES.operations.length;await router.fetch(req('enhanced'),env,{});assert.equal(env.IMAGES.operations.length,count)});
test('rejects invalid mode and missing billable confirmation before transform',async()=>{for(const [mode,body] of [['unknown',{}],['preserve',{confirmBillable:false}]]){const env=await fixture();const r=await router.fetch(req(mode,{body}),env,{});assert.equal(r.status,400);assert.equal(env.IMAGES.operations.length,0)}});
