import test from 'node:test';import assert from 'node:assert/strict';import {assertRenderReady,localReadiness,readinessSnapshot,recordRenderHealth,renderHealth} from '../src/render-health.js';import {Bucket,imageMock} from './security-helpers.mjs';function make(extra={}){let calls=0;return{env:{ARTWORK:new Bucket(),IMAGES:imageMock(),AI:{async run(){calls++;return{}}},...extra},calls:()=>calls}}
test('snapshot never invokes AI',async()=>{const e=make(),s=await readinessSnapshot(e.env,Date.parse('2026-09-29T20:00:00Z'));assert.equal(s.costsAiCall,false);assert.equal(s.modes.high.ready,true);assert.equal(e.calls(),0)});
test('missing binding fails closed',async()=>{const e=make({IMAGES:null});assert.equal(localReadiness(e.env).ready,false);await assert.rejects(assertRenderReady(e.env,'high'),x=>x.reason==='configuration');assert.equal(e.calls(),0)});
test('capacity closes only its mode then expires',async()=>{const e=make({RENDER_CAPACITY_COOLDOWN_SECONDS:'90'}),n=Date.parse('2026-09-29T20:00:00Z');await recordRenderHealth(e.env,'high','failed','capacity',n);assert.equal((await renderHealth(e.env,'high',n+89000)).ready,false);assert.equal((await renderHealth(e.env,'quick',n+1000)).ready,true);assert.equal((await renderHealth(e.env,'high',n+91000)).ready,true);assert.equal(e.calls(),0)});
test('quota blocks preflight then expires without probe',async()=>{const e=make({RENDER_QUOTA_COOLDOWN_SECONDS:'300'}),n=Date.parse('2026-09-29T20:00:00Z');await recordRenderHealth(e.env,'quick','failed','quota',n);await assert.rejects(assertRenderReady(e.env,'quick',n+1000),x=>x.reason==='quota'&&x.status===429);assert.equal((await renderHealth(e.env,'quick',n+301000)).ready,true);assert.equal(e.calls(),0)});
test('success clears previous cooldown',async()=>{const e=make(),n=Date.parse('2026-09-29T20:00:00Z');await recordRenderHealth(e.env,'high','failed','capacity',n);await recordRenderHealth(e.env,'high','success',null,n+1000);assert.equal((await renderHealth(e.env,'high',n+1001)).ready,true)});
test('invalid call-limit config fails closed',async()=>{const e=make({AI_DAILY_CALL_LIMIT:'2.5'}),s=await readinessSnapshot(e.env);assert.equal(s.ok,false);assert.ok(s.local.missing.includes('AI_DAILY_CALL_LIMIT'))});
test('timeout has a conservative five-minute circuit and leaves the other mode ready',async()=>{const e=make({RENDER_TIMEOUT_COOLDOWN_SECONDS:'300'}),n=Date.parse('2026-09-29T20:00:00Z');await recordRenderHealth(e.env,'high','failed','timeout',n);const high=await renderHealth(e.env,'high',n+1000),quick=await renderHealth(e.env,'quick',n+1000);assert.equal(high.ready,false);assert.equal(high.reason,'timeout');assert.equal(quick.ready,true);await assert.rejects(assertRenderReady(e.env,'high',n+1000),x=>x.reason==='timeout'&&x.status===504);assert.equal((await renderHealth(e.env,'high',n+299000)).ready,false);assert.equal((await renderHealth(e.env,'high',n+301000)).ready,true);assert.equal(e.calls(),0)});
test('temporary provider outage has a separate cooldown',async()=>{const e=make({RENDER_UNAVAILABLE_COOLDOWN_SECONDS:'60'}),n=Date.parse('2026-09-29T20:00:00Z');await recordRenderHealth(e.env,'quick','failed','unavailable',n);assert.equal((await renderHealth(e.env,'quick',n+59000)).ready,false);assert.equal((await renderHealth(e.env,'quick',n+61000)).ready,true);assert.equal(e.calls(),0)});
